### ISSUE TITLE
When two different leds are blinking at the same time, they loose sync...

### ISSUE THREAD

**Issue by Rimbaldo** [SethSenpai/singleLEDLibrary#6]
Hi! 

I´m using your library on my attiny85. I have a red and green led, and I managed to create all the different blink times and patterns I want.

But as I´m measuring a battery level, there are conditions I need both red and green to blink in the exact same settings, so I use them like this in the code below, but depending on the battery level, they loose sync and instead of a "yellow" blink, or 
yellow pattern blink, they are not simultaneous.  Sometimes they start together but then, as the voltage measured changes, both leds loose sync...

Could you add an instance to create a led object that requires two or more leds on the same object, so they could perform an action (like blink) together in an exact way? Like a Yellow Led (Led PIN Red, Led PIN Green) ?

This is the part of my code that decides which led blinks or not.

Red == Vermelho
Green == Verde
``
void Update_battery() {

  int pattern[] = {100, 500, 100, 2000};

  if (Voltagem_index == 1) {
    Vermelho.setOffSingle();
    Verde.blinkSingle(1500, 1000);
  }
  if (Voltagem_index == 2) {
    Vermelho.setOffSingle();
    Verde.patternSingle(pattern, 4);
  }
  if (Voltagem_index == 3) {
    Verde.blinkSingle(1500, 1000);
    Vermelho.blinkSingle(1500, 1000);
  }
  if (Voltagem_index == 4) {
    Verde.patternSingle(pattern, 4);
    Vermelho.patternSingle(pattern, 4);
  }
  if (Voltagem_index == 5) {
    Verde.setOffSingle();
    Vermelho.blinkSingle(1500, 1000);
  }
  if (Voltagem_index == 6) {
    Verde.setOffSingle();
    Vermelho.blinkSingle(250);
  }
}
``

**Comment by SethSenpai** [comment]
Hey there,

First of all interesting that they get out of sync at all, I presume that you're running your ATTiny without an external crystal attached to it which might explain how the leds are getting out of step. The internal clock isn't very accurate. I never observed that behaviour in other boards that I tested with, but I also never tested on an MCU that dressed down.

Regarding the modifications. It's a good suggestion and I'll get around to it at some point. But don't expect it any time soon. Implementing it nice and scaleable will be a bit of a faff, but hacking it in is really easy. I suggest you take the libraries source code and add the implementation for your leds yourself.

`sllib::sllib(int pin){
    //make sure to use pwm ports here
    pinMode(pin,OUTPUT);
    digitalWrite(pin,LOW);
    _pin = pin;
}`

Extend this function to have 2 pins and update the functions needed accordingly.

Cheers!

**Comment by Rimbaldo** [comment]
HI!
Ok, I did some changes and it worked now, with no more delays.

Here´s what I did:

I created another Sllib instance that gets _pin and _pin2

pin_2 I set as 255 initially. I doubt there´s any MCU with 255 inputs....

For each of your functions that performed a digital write and analog write,
I added a condition  (copy and paste for almost all of them ) to check if
the _pin2 is different from 255. (If it is, then it was initialized as a
Sllib two leds in the same instance.)So, if it´s different from 255, it
does the same digitalwrite or analogwrite for the _pin2 led that is done
for the _pin led.

I tested and it worked fine, with no delays between them anymore..

As I´m using it to display voltage levels, I had to manually turn off the
green or led when a different voltage level was reached, because sometimes
the blink array would turn on and the previous blink normal on the other
led would still be on.  I´ll attach here your modified code and my code
also..

I didn´t test the PWM yet, because I have no spare PWM pins left on my
attiny, but I´ll test later on a Leonardo.

Thanks for your library. It´s easy to use different blink states, and it´s
not so memory demanding on my Attiny85.

Regards, Rodrigo

Here is my code that worked now: Used two patterns arrays because I didn´t
know if one would mess with the other for the other color.

...
sllib Verde(LED_VERDE);
sllib Vermelho(LED_VERMELHO);
sllib Amarelo(LED_VERDE, LED_VERMELHO);
...

void Update_battery() {

  int pattern1[] = {100, 500, 100, 2000};
  int pattern2[] = {100, 500, 100, 2000};

  if (Voltagem_index == 1) {
    Vermelho.setOffSingle();                                    // Need to
turn off RED so Green works normally
    Verde.blinkSingle(1500, 1000);
  }
  if (Voltagem_index == 2) {
    Vermelho.setOffSingle();                                    // Need to
turn off RED so Green pattern works normally
    Verde.patternSingle(pattern1, 4);
  }
  if (Voltagem_index == 3) {
    Amarelo.blinkSingle(1500, 1000);                     // This is the new
dual color (R+G)  "YELLOW" at the same instance
  }
  if (Voltagem_index == 4) {
    Amarelo.patternSingle(pattern2, 4);                  // And as a pattern
   }
  if (Voltagem_index == 5) {
    Verde.setOffSingle();                                        // For RED
to work normally, need to turn off GREEN
    Vermelho.blinkSingle(750, 500);
  }
  if (Voltagem_index == 6) {
    Verde.setOffSingle();                                        // Same
here
    Vermelho.blinkSingle(125);
  }
}





<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui., 3 de set. de 2020 às 15:06, Pim Ostendorf <notifications@github.com>
escreveu:
