### ISSUE TITLE
reverse polarity ?

### ISSUE THREAD

**Issue by Shedevri** [SethSenpai/singleLEDLibrary#9]

**Comment by Shedevri** [comment]
what to do if led is turned on by ground?

**Comment by SethSenpai** [comment]
If I understand you correctly you're asking what to do when the LED is turned on when the pin goes low? In that case the functions are just reversed. AKA setLedOff turns into setLedOn and vice versa. You could implement a switch or something along the lines that autoreverse these functions for you to keep readability.

**Comment by Shedevri** [comment]
yes, but other functions also change and do not work correctly

**Comment by SethSenpai** [comment]
What behaviour are you seeing? There should be no reason the other functions shouldn't work. Just inverted in its output.
